[profile.release]
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true

[package]
name = "rtv2"
version = "0.1.0"
edition = "2024"
autobenches = false

[dev-dependencies]
cargo-show-asm = "0.2.62"
divan = "0.1.21"
rand = "0.10.2"

[[bench]]
name = "main"
harness = false

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
config = { version = "0.15.25", default-features = false, features = ["yaml"] }
crossterm = "0.29.0"
libspa = "0.10.0"
num-traits = "0.2.19"
pipewire = "0.10.0"
realfft = "3.5.0"
rustfft = "6.4.1"
serde = { version = "1.0.229", features = ["derive"] }
vmcircbuffer = "0.0.16"
