controller:
  type: decimating # or monolithic

  # core information required for all controller types
  core:
    sample_rate: 48000
    transform_size: 1024
    framerate: 30

  # the number of times we recursively apply a half band low pass filter, effectively halving the nyquist frequency but doubling the observation window
  decimations: 7
  # the number of decimations to display. Initial decimations may yield frequency spectrum data higher than you require, but these decimations are still required to "get to" lower decimations
  displayed_decimations: 5

  # Set up the half band FIR filter used with a decimating controller
  filter:
    # ideal frequency cutoff relative to the Nyquist frequency
    normalised_cutoff: 0.5

    # set up the window function used with the half band filter
    # the tap num for the FIR filter is equal to the number of samples in the window
    window:
      # the window function
      function: blackman
      # the number of FIR filter taps
      samples: 131

display:
  # by default, the display will use the width and height of the terminal from the program is run.
  # setting them manually will attempt to resize the terminal
  # this may look very messy if it fails silently
  # display_width:
  # display_height:
  #
  bar_width: 1



merger:

  # The method used to "realise" a complex FFT output value back to a single float
  # magnitude_squared, magnitude, real or imaginary
  realisor: magnitude_squared
  # The method used to aggregate multiple FFT output "bins" which correspond to a single displayed bar
  # max, mean or sum
  # due to normalisation sum yields the same result as mean when each output has the same number of input buckets (linear mode)
  aggregator: mean

  # The type of merger (Linear or Exponential) and any related arguments
  merger_type:

    # Linear merging simply averages an equal number of FFT output frequency "bins"
    # Visually, linear merging looks poor when used with a decimating controller, as output between decimation stages will overlap
    #   type: linear

    # Exponential merging attempts to visually scale frequency spectrum data similarly to how it is heard
    # allows display of traditional musical tones and semitones
    # when used with a decimating controller, the tuning frequency should be set to the highest displayed octave
    # as each decimation lowers the analysis by 1 octave, the range of notes displayed is controlled by the number of decimations and the number of outputs (display bars)
    # hence bars_per_octave and starting_note_offset are ignored when a decimating controller is used

    type: exponential

    # frequency of a note that all other notes will be set relative to
    tuning_frequency: 8000

    # the number of notes in an octave (i.e. the number of notes for each doubling of frequency)
    # set this to 12 to display semitones or 6 to average to full tones etc
    # this should be left to set automatically when used with a decimating controller
    # bars_per_octave: 12

    # the number of bars below the tuning frequency your first note is
    # this only really exists so that the tuning frequency can be set independently of the first note to display- e.g. tune A4 at 440hz but the "0th" note is A0 (offset -48) at 27.5hz
    # there is no difference in practice between doing this and setting the tuning frequency at 27.5hz with zero offset
    # this should be left to set automatically when used with a decimating controller
    # starting_note_offset: -12



normaliser:
  # use a constant factor when normalising output
  #type: constant
  #factor: 1000

  # grow/decay the normalisation factor when the maximum in a given frame exceeds/falls under a set factor of the "set" maximum
  # output is normalised so a full height bar = set maximum * growth_factor
  # the "set maximum" is the most recent maximum to cause a change in growth and decay factors by exceeding or falling under the thresholds set by the previous one
  type: factor
  growth_factor: 2.0
  decay_factor: 0.2
