# FFT and display settings
transform_size: 1024
sample_rate: 48000
framerate: 30

# Linear merging needs no additional settings.
# merger:
#  type: linear

# Exponential merging can be selected instead:
merger:
  type: exponential
  tuning_frequency: 1760
  bars_per_octave: 12
  starting_note_offset: -12
